services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ${USERPROFILE}\\.kube\\config:/root/.kube/config:ro  # For Windows (adjust if necessary)
      - //var/run/docker.sock:/var/run/docker.sock 
    network_mode: bridge
    environment:
      - KUBERNETES_HOST=localhost
      - KUBERNETES_PORT=8080
      - PYTHONUNBUFFERED=1

  frontend:
    image: python:3.12-slim
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    command: python3 -m http.server 8080
    ports:
      - "8080:8080"
    network_mode: bridge
